"""add sub_category

Revision ID: 617fcad71884
Revises: 9793945716d9
Create Date: 2024-07-04 13:03:59.680473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617fcad71884'
down_revision: Union[str, None] = '9793945716d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('sub_category', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'sub_category')
    # ### end Alembic commands ###
