"""remove type from transaction and add it to category

Revision ID: b0577e970998
Revises: f61571610056
Create Date: 2024-07-04 12:35:40.707864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0577e970998'
down_revision: Union[str, None] = 'f61571610056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.String(length=10), nullable=False))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
